using Abhyanvaya.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Abhyanvaya.Infrastructure.Persistence.Migrations;

/// <summary>
/// Ensures DashboardPreferences exists with RefreshIntervalSeconds (and related AI31.8 columns).
/// Idempotent — safe if scripts/Apply_AI31_* already applied.
/// </summary>
[DbContext(typeof(ApplicationDbContext))]
[Migration("20260808230000_AI31_DashboardPreferencesRefreshColumns")]
public partial class AI31_DashboardPreferencesRefreshColumns : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "DashboardPreferences" (
              "Id" integer GENERATED BY DEFAULT AS IDENTITY,
              "TenantId" integer NOT NULL,
              "UserId" integer NOT NULL,
              "RoleScope" character varying(64) NOT NULL,
              "DefaultLandingPage" character varying(128) NOT NULL DEFAULT 'command-center',
              "CompactMode" boolean NOT NULL DEFAULT FALSE,
              "HiddenWidgetsJson" text NOT NULL DEFAULT '[]',
              "WidgetOrderJson" text NOT NULL DEFAULT '[]',
              "PinnedWidgetsJson" text NOT NULL DEFAULT '[]',
              "FilterJson" text NOT NULL DEFAULT '{}',
              "RefreshIntervalSeconds" integer NOT NULL DEFAULT 60,
              "HighContrast" boolean NOT NULL DEFAULT FALSE,
              "CreatedDate" timestamp with time zone NOT NULL,
              "CreatedBy" integer NULL,
              "UpdatedDate" timestamp with time zone NULL,
              "UpdatedBy" integer NULL,
              "IsDeleted" boolean NOT NULL DEFAULT FALSE,
              CONSTRAINT "PK_DashboardPreferences" PRIMARY KEY ("Id")
            );

            ALTER TABLE "DashboardPreferences" ADD COLUMN IF NOT EXISTS "PinnedWidgetsJson" text NOT NULL DEFAULT '[]';
            ALTER TABLE "DashboardPreferences" ADD COLUMN IF NOT EXISTS "FilterJson" text NOT NULL DEFAULT '{}';
            ALTER TABLE "DashboardPreferences" ADD COLUMN IF NOT EXISTS "RefreshIntervalSeconds" integer NOT NULL DEFAULT 60;
            ALTER TABLE "DashboardPreferences" ADD COLUMN IF NOT EXISTS "HighContrast" boolean NOT NULL DEFAULT FALSE;

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_DashboardPreferences_Tenant_User_Role"
              ON "DashboardPreferences" ("TenantId", "UserId", "RoleScope")
              WHERE "IsDeleted" = FALSE;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Non-destructive: keep preference columns (additive hardening).
    }
}
