/** Mirrors backend `Abhyanvaya.Domain.Authorization.PermissionKeys` (JWT `permission` claims). */
export const PermissionKeys = {
  StudentsView: "Students.View",
  StudentsManage: "Students.Manage",
  AttendanceView: "Attendance.View",
  AttendanceManage: "Attendance.Manage",
  ReportsView: "Reports.View",
  SetupSubjectsManage: "Setup.Subjects.Manage",
  SetupDepartmentsManage: "Setup.Departments.Manage",
  SetupStaffManage: "Setup.Staff.Manage",
  DashboardView: "Dashboard.View",
  OrganizationManage: "Organization.Manage",
  MasterView: "Master.View",
  SetupLookupsManage: "Setup.Lookups.Manage",
  SetupCoursesManage: "Setup.Courses.Manage",
  SetupGroupsManage: "Setup.Groups.Manage",
  SetupSemestersManage: "Setup.Semesters.Manage",
  EnrollmentView: "Enrollment.View",
  EnrollmentManage: "Enrollment.Manage",
  SchedulingView: "Scheduling.View",
  SchedulingManage: "Scheduling.Manage",
  SchedulingRoomAvailabilityView: "Scheduling.RoomAvailability.View",
  SchedulingRoomAvailabilityManage: "Scheduling.RoomAvailability.Manage",
  SchedulingFacultyAvailabilityView: "Scheduling.FacultyAvailability.View",
  SchedulingFacultyAvailabilityManage: "Scheduling.FacultyAvailability.Manage",
  SchedulingTemplateView: "Scheduling.Template.View",
  SchedulingTemplateManage: "Scheduling.Template.Manage",
  SchedulingFacultyPreferencesView: "Scheduling.FacultyPreferences.View",
  SchedulingFacultyPreferencesManage: "Scheduling.FacultyPreferences.Manage",
  SchedulingRoomFeaturesView: "Scheduling.RoomFeatures.View",
  SchedulingRoomFeaturesManage: "Scheduling.RoomFeatures.Manage",
  SchedulingSubjectDeliveryView: "Scheduling.SubjectDelivery.View",
  SchedulingSubjectDeliveryManage: "Scheduling.SubjectDelivery.Manage",
  SchedulingHolidayTypesView: "Scheduling.HolidayTypes.View",
  SchedulingHolidayTypesManage: "Scheduling.HolidayTypes.Manage",
  SchedulingTimetableView: "Scheduling.Timetable.View",
  SchedulingTimetableManage: "Scheduling.Timetable.Manage",
  SchedulingVersionView: "Scheduling.Version.View",
  SchedulingVersionManage: "Scheduling.Version.Manage",
  SchedulingReview: "Scheduling.Review",
  SchedulingApprove: "Scheduling.Approve",
  SchedulingPublish: "Scheduling.Publish",
  SchedulingArchive: "Scheduling.Archive",
  SchedulingClone: "Scheduling.Clone",
  SchedulingHistoryView: "Scheduling.History.View",
  SchedulingVersionCompareView: "Scheduling.VersionCompare.View",
  SchedulingVersionCompareExport: "Scheduling.VersionCompare.Export",
  SchedulingApprovalCommentsView: "Scheduling.ApprovalComments.View",
  SchedulingApprovalCommentsManage: "Scheduling.ApprovalComments.Manage",
  SchedulingFreeze: "Scheduling.Freeze",
  SchedulingUnlock: "Scheduling.Unlock",
  SchedulingArchiveView: "Scheduling.Archive.View",
  SchedulingArchiveManage: "Scheduling.Archive.Manage",
  SchedulingConflictView: "Scheduling.Conflict.View",
  SchedulingConflictManage: "Scheduling.Conflict.Manage",
} as const;

export type PermissionKey = (typeof PermissionKeys)[keyof typeof PermissionKeys];
