-- AI29.1A.7 — Academic Platform Observability (additive).

CREATE TABLE IF NOT EXISTS "AcademicArchitectureTrends" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "RecordedUtc" timestamp with time zone NOT NULL,
  "Score" integer NOT NULL DEFAULT 0,
  "DependencyViolations" integer NOT NULL DEFAULT 0,
  "ForbiddenReferences" integer NOT NULL DEFAULT 0,
  "LayerViolations" integer NOT NULL DEFAULT 0,
  "Summary" character varying(2000) NULL,
  "TenantId" integer NOT NULL,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_AcademicArchitectureTrends" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_AcademicArchitectureTrends_Tenant_Recorded"
  ON "AcademicArchitectureTrends" ("TenantId", "RecordedUtc");

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '__EFMigrationsHistory') THEN
    IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260807120000_AI29_1A7_Observability') THEN
      INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20260807120000_AI29_1A7_Observability', '8.0.0');
    END IF;
  END IF;
END $$;
