-- AI29.1A.5 — Academic Hierarchy Enterprise Hardening (idempotent, additive, non-destructive).
-- Keeps Program Active/Inactive/Archived. Does not introduce Planning/Open/Operational/Closed on Program.

-- Program optional metadata
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Programs') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Programs' AND column_name = 'Icon') THEN
      ALTER TABLE "Programs" ADD COLUMN "Icon" character varying(64) NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Programs' AND column_name = 'ThemeColor') THEN
      ALTER TABLE "Programs" ADD COLUMN "ThemeColor" character varying(32) NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Programs' AND column_name = 'AcademicCalendarId') THEN
      ALTER TABLE "Programs" ADD COLUMN "AcademicCalendarId" integer NULL;
    END IF;
  END IF;
END $$;

-- DisplayOrder on academic masters (additive defaults)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Course') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Course' AND column_name = 'DisplayOrder') THEN
      ALTER TABLE "Course" ADD COLUMN "DisplayOrder" integer NOT NULL DEFAULT 0;
    END IF;
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Group') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Group' AND column_name = 'DisplayOrder') THEN
      ALTER TABLE "Group" ADD COLUMN "DisplayOrder" integer NOT NULL DEFAULT 0;
    END IF;
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Semester') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Semester' AND column_name = 'DisplayOrder') THEN
      ALTER TABLE "Semester" ADD COLUMN "DisplayOrder" integer NOT NULL DEFAULT 0;
    END IF;
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Subject') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Subject' AND column_name = 'DisplayOrder') THEN
      ALTER TABLE "Subject" ADD COLUMN "DisplayOrder" integer NOT NULL DEFAULT 0;
    END IF;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "ProgramPolicies" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "ProgramId" integer NOT NULL,
  "MinimumAttendancePercent" numeric NULL,
  "CreditsRequired" numeric NULL,
  "PassMarks" numeric NULL,
  "MaximumBacklogs" integer NULL,
  "MaximumSubjects" integer NULL,
  "AcademicRules" character varying(4000) NULL,
  "TenantId" integer NOT NULL,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_ProgramPolicies" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProgramPolicies_Tenant_Program"
  ON "ProgramPolicies" ("TenantId", "ProgramId")
  WHERE "IsDeleted" = FALSE;

-- Existing Program.Status values (Active/Archived) are preserved as-is.
-- Inactive is newly allowed via API validation; no destructive remaps.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '__EFMigrationsHistory') THEN
    IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806140000_AI29_1A5_EnterpriseHardening') THEN
      INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20260806140000_AI29_1A5_EnterpriseHardening', '8.0.0');
    END IF;
  END IF;
END $$;
