-- AI29.1A — Program Management & Academic Hierarchy (idempotent, additive, non-destructive).

CREATE TABLE IF NOT EXISTS "Programs" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "CollegeId" integer NOT NULL,
  "ProgramCode" character varying(32) NOT NULL,
  "ProgramName" character varying(128) NOT NULL,
  "Description" character varying(512) NULL,
  "DisplayOrder" integer NOT NULL DEFAULT 0,
  "IsActive" boolean NOT NULL DEFAULT TRUE,
  "Status" character varying(32) NOT NULL DEFAULT 'Active',
  "TenantId" integer NOT NULL,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_Programs" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Programs_Tenant_Code"
  ON "Programs" ("TenantId", "ProgramCode")
  WHERE "IsDeleted" = FALSE;

CREATE TABLE IF NOT EXISTS "TenantAcademicConfigurations" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "CollegeId" integer NOT NULL,
  "EnablePrograms" boolean NOT NULL DEFAULT FALSE,
  "TenantId" integer NOT NULL,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_TenantAcademicConfigurations" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_TenantAcademicConfigurations_Tenant"
  ON "TenantAcademicConfigurations" ("TenantId")
  WHERE "IsDeleted" = FALSE;

-- Additive Course.ProgramId (nullable) — table name is "Course"
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'Course'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'Course' AND column_name = 'ProgramId'
    ) THEN
      ALTER TABLE "Course" ADD COLUMN "ProgramId" integer NULL;
    END IF;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_Course_ProgramId" ON "Course" ("ProgramId");

-- Permissions Program.*
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "Permission" WHERE "Key" = 'Program.View') THEN
    INSERT INTO "Permission" ("Id", "Key", "Resource", "Action") VALUES
      (220, 'Program.View', 'Program', 'View'),
      (221, 'Program.Create', 'Program', 'Create'),
      (222, 'Program.Edit', 'Program', 'Edit'),
      (223, 'Program.Delete', 'Program', 'Delete'),
      (224, 'Program.Manage', 'Program', 'Manage');
  END IF;

  IF EXISTS (SELECT 1 FROM "ApplicationRole" WHERE "Id" = 100) THEN
    INSERT INTO "ApplicationRolePermission" ("ApplicationRoleId", "PermissionId")
    SELECT 100, p."Id"
    FROM "Permission" p
    WHERE p."Id" BETWEEN 220 AND 224
      AND NOT EXISTS (
        SELECT 1 FROM "ApplicationRolePermission" arp
        WHERE arp."ApplicationRoleId" = 100 AND arp."PermissionId" = p."Id"
      );
  END IF;
EXCEPTION WHEN undefined_table THEN
  RAISE NOTICE 'Permission tables not ready; skip AI29.1A permission seed.';
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '__EFMigrationsHistory') THEN
    IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806120000_AI29_1A_Programs') THEN
      INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20260806120000_AI29_1A_Programs', '8.0.0');
    END IF;
  END IF;
END $$;
