-- AI22.8 / AI22.8.5 — idempotent schema apply for attendance recovery.
-- Fixes: 42703 column LastActivityUtc does not exist

ALTER TABLE "AttendanceSession"
  ADD COLUMN IF NOT EXISTS "WorkflowStatus" integer NOT NULL DEFAULT 0;

ALTER TABLE "AttendanceSession"
  ADD COLUMN IF NOT EXISTS "LastActivityUtc" timestamp with time zone NULL;

ALTER TABLE "AttendanceSession"
  ADD COLUMN IF NOT EXISTS "ResumeCheckpointJson" text NULL;

ALTER TABLE "AttendanceSession"
  ADD COLUMN IF NOT EXISTS "WorkflowExpiredUtc" timestamp with time zone NULL;

ALTER TABLE "SchedulingWorkspacePreference"
  ADD COLUMN IF NOT EXISTS "RecoveryPreferencesJson" text NOT NULL
  DEFAULT '{"promptOnLogin":true,"dismissAutoResumeUntilUtc":null}';

CREATE TABLE IF NOT EXISTS "AttendanceRetryHistory" (
  "Id" uuid NOT NULL,
  "TenantId" integer NOT NULL,
  "AttendanceSessionId" uuid NOT NULL,
  "Stage" character varying(64) NOT NULL,
  "Action" character varying(64) NOT NULL,
  "Success" boolean NOT NULL,
  "ErrorMessage" character varying(2000) NULL,
  "WorkflowStatusBefore" integer NULL,
  "WorkflowStatusAfter" integer NULL,
  "PerformedBy" integer NOT NULL,
  "PerformedUtc" timestamp with time zone NOT NULL,
  CONSTRAINT "PK_AttendanceRetryHistory" PRIMARY KEY ("Id"),
  CONSTRAINT "FK_AttendanceRetryHistory_AttendanceSession_AttendanceSessionId"
    FOREIGN KEY ("AttendanceSessionId") REFERENCES "AttendanceSession" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AttendanceSession_TenantId_WorkflowStatus_LastActivityUtc"
  ON "AttendanceSession" ("TenantId", "WorkflowStatus", "LastActivityUtc");

CREATE INDEX IF NOT EXISTS "IX_AttendanceSession_TenantId_StaffId_WorkflowExpiredUtc"
  ON "AttendanceSession" ("TenantId", "StaffId", "WorkflowExpiredUtc");

CREATE INDEX IF NOT EXISTS "IX_AttendanceRetryHistory_TenantId_AttendanceSessionId_PerformedUtc"
  ON "AttendanceRetryHistory" ("TenantId", "AttendanceSessionId", "PerformedUtc");

CREATE TABLE IF NOT EXISTS "AttendanceRecoveryPreference" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "TenantId" integer NOT NULL,
  "StaffId" integer NOT NULL,
  "UserId" integer NOT NULL,
  "AutoSaveFrequencySeconds" integer NOT NULL DEFAULT 30,
  "ResumeConfirmation" boolean NOT NULL DEFAULT TRUE,
  "DefaultLandingPage" character varying(64) NOT NULL DEFAULT 'pending',
  "NotificationsEnabled" boolean NOT NULL DEFAULT TRUE,
  "SessionTimeoutWarning" boolean NOT NULL DEFAULT TRUE,
  "SessionTimeoutWarningMinutes" integer NOT NULL DEFAULT 30,
  "PromptOnLogin" boolean NOT NULL DEFAULT TRUE,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_AttendanceRecoveryPreference" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_AttendanceRecoveryPreference_TenantId_StaffId"
  ON "AttendanceRecoveryPreference" ("TenantId", "StaffId");

CREATE INDEX IF NOT EXISTS "IX_AttendanceRecoveryPreference_TenantId_UserId"
  ON "AttendanceRecoveryPreference" ("TenantId", "UserId");

-- Record in EF history when table exists (ignore if already present).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '__EFMigrationsHistory') THEN
    IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803123000_AI22_8_AttendanceRecovery') THEN
      INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20260803123000_AI22_8_AttendanceRecovery', '8.0.0');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803180000_AI22_8_5_AttendanceRecoveryPreference') THEN
      INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20260803180000_AI22_8_5_AttendanceRecoveryPreference', '8.0.0');
    END IF;
  END IF;
END $$;
