-- AI29 — Academic Structure & Section Management (idempotent, non-destructive).

CREATE TABLE IF NOT EXISTS "Sections" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "CollegeId" integer NOT NULL,
  "AcademicYearId" integer NOT NULL,
  "CourseId" integer NOT NULL,
  "GroupId" integer NOT NULL,
  "SemesterId" integer NOT NULL,
  "SectionCode" character varying(32) NOT NULL,
  "SectionName" character varying(128) NOT NULL,
  "DisplayOrder" integer NOT NULL DEFAULT 0,
  "MaximumStrength" integer NOT NULL DEFAULT 60,
  "Status" character varying(32) NOT NULL DEFAULT 'Active',
  "TenantId" integer NOT NULL,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_Sections" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Sections_Tenant_Scope_Code"
  ON "Sections" ("TenantId", "AcademicYearId", "CourseId", "GroupId", "SemesterId", "SectionCode")
  WHERE "IsDeleted" = FALSE;

CREATE TABLE IF NOT EXISTS "StudentSections" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "StudentId" integer NOT NULL,
  "SectionId" integer NOT NULL,
  "EffectiveFrom" date NOT NULL,
  "EffectiveTo" date NULL,
  "IsCurrent" boolean NOT NULL DEFAULT TRUE,
  "TransferReason" character varying(512) NULL,
  "TenantId" integer NOT NULL,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_StudentSections" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_StudentSections_Student_Current"
  ON "StudentSections" ("TenantId", "StudentId", "IsCurrent")
  WHERE "IsDeleted" = FALSE;

CREATE TABLE IF NOT EXISTS "FacultySectionAssignments" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "FacultyId" integer NOT NULL,
  "SectionId" integer NOT NULL,
  "AcademicYearId" integer NOT NULL,
  "Role" character varying(32) NOT NULL DEFAULT 'Primary',
  "EffectiveFrom" date NOT NULL,
  "EffectiveTo" date NULL,
  "IsCurrent" boolean NOT NULL DEFAULT TRUE,
  "TenantId" integer NOT NULL,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_FacultySectionAssignments" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_FacultySectionAssignments_Faculty"
  ON "FacultySectionAssignments" ("TenantId", "FacultyId", "IsCurrent")
  WHERE "IsDeleted" = FALSE;

CREATE TABLE IF NOT EXISTS "TimetableSections" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "TimetableId" integer NOT NULL,
  "TimetableEntryId" integer NULL,
  "SectionId" integer NOT NULL,
  "TenantId" integer NOT NULL,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_TimetableSections" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_TimetableSections_Entry_Section"
  ON "TimetableSections" ("TenantId", "TimetableId", "TimetableEntryId", "SectionId")
  WHERE "IsDeleted" = FALSE;

CREATE TABLE IF NOT EXISTS "AttendanceSessionSections" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "AttendanceSessionId" uuid NOT NULL,
  "SectionId" integer NOT NULL,
  "TenantId" integer NOT NULL,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_AttendanceSessionSections" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_AttendanceSessionSections_Session"
  ON "AttendanceSessionSections" ("TenantId", "AttendanceSessionId")
  WHERE "IsDeleted" = FALSE;

CREATE TABLE IF NOT EXISTS "SectionAllocationPreferences" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "CollegeId" integer NOT NULL,
  "AcademicYearId" integer NOT NULL,
  "CourseId" integer NOT NULL,
  "GroupId" integer NOT NULL,
  "SemesterId" integer NOT NULL,
  "Strategy" character varying(64) NOT NULL DEFAULT 'Alphabetical',
  "TenantId" integer NOT NULL,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_SectionAllocationPreferences" PRIMARY KEY ("Id")
);

-- Permissions (Section.*) — Admin role id 100 when present (table names match EF seed)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "Permission" WHERE "Key" = 'Section.View') THEN
    INSERT INTO "Permission" ("Id", "Key", "Resource", "Action") VALUES
      (210, 'Section.View', 'Section', 'View'),
      (211, 'Section.Create', 'Section', 'Create'),
      (212, 'Section.Edit', 'Section', 'Edit'),
      (213, 'Section.Delete', 'Section', 'Delete'),
      (214, 'Section.AssignStudents', 'Section', 'AssignStudents'),
      (215, 'Section.AssignFaculty', 'Section', 'AssignFaculty');
  END IF;

  IF EXISTS (SELECT 1 FROM "ApplicationRole" WHERE "Id" = 100) THEN
    INSERT INTO "ApplicationRolePermission" ("ApplicationRoleId", "PermissionId")
    SELECT 100, p."Id"
    FROM "Permission" p
    WHERE p."Id" BETWEEN 210 AND 215
      AND NOT EXISTS (
        SELECT 1 FROM "ApplicationRolePermission" arp
        WHERE arp."ApplicationRoleId" = 100 AND arp."PermissionId" = p."Id"
      );
  END IF;
EXCEPTION WHEN undefined_table THEN
  RAISE NOTICE 'Permission tables not ready; skip AI29 permission seed.';
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '__EFMigrationsHistory') THEN
    IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805120000_AI29_AcademicSections') THEN
      INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20260805120000_AI29_AcademicSections', '8.0.0');
    END IF;
  END IF;
END $$;
