-- AI29.1A.6 — Academic Hierarchy Performance & Architecture Guard (additive).
-- Snapshots are feature-flagged (AcademicHierarchy:EnableDailySnapshots = false by default).

CREATE TABLE IF NOT EXISTS "AcademicHierarchySnapshots" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "SnapshotDate" date NOT NULL,
  "Programs" integer NOT NULL DEFAULT 0,
  "Courses" integer NOT NULL DEFAULT 0,
  "Groups" integer NOT NULL DEFAULT 0,
  "Semesters" integer NOT NULL DEFAULT 0,
  "Sections" integer NOT NULL DEFAULT 0,
  "Subjects" integer NOT NULL DEFAULT 0,
  "HierarchyJson" text NOT NULL DEFAULT '[]',
  "GeneratedDate" timestamp with time zone NOT NULL,
  "TenantId" integer NOT NULL,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_AcademicHierarchySnapshots" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_AcademicHierarchySnapshots_Tenant_Date"
  ON "AcademicHierarchySnapshots" ("TenantId", "SnapshotDate")
  WHERE "IsDeleted" = FALSE;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '__EFMigrationsHistory') THEN
    IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806160000_AI29_1A6_PerformanceGuard') THEN
      INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20260806160000_AI29_1A6_PerformanceGuard', '8.0.0');
    END IF;
  END IF;
END $$;
