-- AI31.6 — idempotent schema for dashboard preferences + notification user state.

CREATE TABLE IF NOT EXISTS "DashboardPreferences" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "TenantId" integer NOT NULL,
  "UserId" integer NOT NULL,
  "RoleScope" character varying(64) NOT NULL,
  "DefaultLandingPage" character varying(128) NOT NULL DEFAULT 'command-center',
  "CompactMode" boolean NOT NULL DEFAULT FALSE,
  "HiddenWidgetsJson" text NOT NULL DEFAULT '[]',
  "WidgetOrderJson" text NOT NULL DEFAULT '[]',
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_DashboardPreferences" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_DashboardPreferences_Tenant_User_Role"
  ON "DashboardPreferences" ("TenantId", "UserId", "RoleScope")
  WHERE "IsDeleted" = FALSE;

CREATE TABLE IF NOT EXISTS "EnterpriseNotificationStates" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "TenantId" integer NOT NULL,
  "UserId" integer NOT NULL,
  "NotificationId" character varying(256) NOT NULL,
  "IsRead" boolean NOT NULL DEFAULT FALSE,
  "IsPinned" boolean NOT NULL DEFAULT FALSE,
  "IsDismissed" boolean NOT NULL DEFAULT FALSE,
  "IsArchived" boolean NOT NULL DEFAULT FALSE,
  "CreatedDate" timestamp with time zone NOT NULL,
  "CreatedBy" integer NULL,
  "UpdatedDate" timestamp with time zone NULL,
  "UpdatedBy" integer NULL,
  "IsDeleted" boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT "PK_EnterpriseNotificationStates" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_EnterpriseNotificationStates_Tenant_User_Notification"
  ON "EnterpriseNotificationStates" ("TenantId", "UserId", "NotificationId")
  WHERE "IsDeleted" = FALSE;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '__EFMigrationsHistory') THEN
    IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804120000_AI31_6_EnterpriseDashboards') THEN
      INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20260804120000_AI31_6_EnterpriseDashboards', '8.0.0');
    END IF;
  END IF;
END $$;
